name: SpeedX
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  fluttertoast: ^8.0.9
  logger: ^2.4.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
