// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACG1rNrasqzZJvj-J63ovHok8PIOKyR2o',
    appId: '1:412796394600:web:4f438a8563cd6b4fc52fdd',
    messagingSenderId: '412796394600',
    projectId: 'speedx-74401',
    authDomain: 'speedx-74401.firebaseapp.com',
    storageBucket: 'speedx-74401.appspot.com',
    measurementId: 'G-1LC94GQFG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnBpWml80rwbciQEwg3ikjfUDeaJ24y5Q',
    appId: '1:412796394600:android:5e01edc1cf2a03c0c52fdd',
    messagingSenderId: '412796394600',
    projectId: 'speedx-74401',
    storageBucket: 'speedx-74401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBHBOE3vWyeineOIKfAh3mdM2z4Dc6KU',
    appId: '1:412796394600:ios:8c39984fb06361c3c52fdd',
    messagingSenderId: '412796394600',
    projectId: 'speedx-74401',
    storageBucket: 'speedx-74401.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzBHBOE3vWyeineOIKfAh3mdM2z4Dc6KU',
    appId: '1:412796394600:ios:8c39984fb06361c3c52fdd',
    messagingSenderId: '412796394600',
    projectId: 'speedx-74401',
    storageBucket: 'speedx-74401.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACG1rNrasqzZJvj-J63ovHok8PIOKyR2o',
    appId: '1:412796394600:web:d7d2ff78338a0837c52fdd',
    messagingSenderId: '412796394600',
    projectId: 'speedx-74401',
    authDomain: 'speedx-74401.firebaseapp.com',
    storageBucket: 'speedx-74401.appspot.com',
    measurementId: 'G-XZY6KFKN0C',
  );
}
